<?php

namespace AppBundle\Repository;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySlug($slug)
    {
        $qb = $this->createQueryBuilder('t');

        $qb
            ->where('t.slug = :slug')
            ->setParameter('slug', $slug)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
